# Generated by Django 4.1.4 on 2022-12-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_project_created_at_remove_project_delete_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
